## This notebook contains some simple tests for the Sparse Tensor / SparseNDArray extension for Needle

In [4]:
import os
import sys

In [5]:
sys.path.append('./python/')

In [6]:
import needle
import numpy as np

from needle.backend_ndarray import SparseNDArray
from needle.backend_ndarray import NDArray

from needle.backend_ndarray import ndarray, sparse_ndarray

In [7]:
loc = np.array([[0,1,2],[1,1,0],[0,1,2]])
val = np.array([2,3,4])
shape = (3,3,3)
nnz = 3
arr = SparseNDArray(loc, val, shape, device=sparse_ndarray.cpu())

In [8]:
arr + 10

NDArray(locations=[[0. 1. 2.]
 [1. 1. 0.]
 [0. 1. 2.]]
values=[12. 13. 14.], device=cpu())

In [9]:
print(arr._shape)
print(arr._handle.nnz)
print(arr._handle.nnz)

(3, 3, 3)
3
3


In [10]:
loc1 = np.array([[0,1,2],[0,1,0],[0,1,2]])
arr1 = SparseNDArray(loc1, val, shape)
arr1

NDArray(locations=[[0. 1. 2.]
 [0. 1. 0.]
 [0. 1. 2.]]
values=[2. 3. 4.], device=cpu())

In [11]:
arr + arr1

NDArray(locations=[[0. 0. 1. 2.]
 [0. 1. 1. 0.]
 [0. 0. 1. 2.]]
values=[2. 2. 6. 8.], device=cpu())

In [12]:
arr * arr1

[20.0, 13.0]


NDArray(locations=[[1. 2.]
 [1. 0.]
 [1. 2.]]
values=[ 9. 16.], device=cpu())

In [13]:
arr_d = arr.to_dense()
arr_d

<class 'numpy.ndarray'> [[[0. 0. 0.]
  [2. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 3. 0.]
  [0. 0. 0.]]

 [[0. 0. 4.]
  [0. 0. 0.]
  [0. 0. 0.]]]


NDArray([[[0. 0. 0.]
  [2. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 3. 0.]
  [0. 0. 0.]]

 [[0. 0. 4.]
  [0. 0. 0.]
  [0. 0. 0.]]], device=cpu())

In [14]:
# TO BE IMPLEMENTED: this requires additional efforts, since currently implementing to_sparse
# in NDArray will incur a cyclic import situation
# arr_d.to_sparse()