In [1]:
import os
import sys

In [2]:
sys.path.append('./python/')

In [3]:
import needle
import numpy as np

from needle.backend_ndarray import SparseNDArray, cpu
from needle.backend_ndarray import NDArray

In [4]:
loc = np.array([[0,1,2],[1,1,0],[0,1,2]])
val = np.array([2,3,4])
shape = (3,3,3)
nnz = 3
arr = SparseNDArray(loc, val, shape, device=cpu())

In [5]:
strides = SparseNDArray.compact_strides(shape)
strides

(9, 3, 1)

In [6]:
loc1d = SparseNDArray.convert_loc_to_1d(shape, loc)
loc1d

array([ 3, 13, 20])

In [7]:
SparseNDArray.convert_1d_to_loc(shape, loc1d)

array([[0., 1., 2.],
       [1., 1., 0.],
       [0., 1., 2.]])

In [8]:
print(arr._shape)
print(arr._handle.nnz)
print(arr._handle.nnz)

(3, 3, 3)
3
3


In [8]:
arr.numpy_value()

array([2., 3., 4.], dtype=float32)

In [9]:
arr.numpy_location()

array([1., 4., 6.], dtype=float32)

In [10]:
arr = NDArray(loc)
arr

NDArray([[0. 1. 2.]
 [1. 1. 0.]], device=cpu_numpy())

In [ ]:
loc.flatten()

In [12]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
a[:,0] = [1,2,3]
a

array([[1., 0., 0.],
       [2., 0., 0.],
       [3., 0., 0.]])

In [15]:
1//3

0